apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: wp-svc
  labels:
    app: wp
spec:
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: wp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wp_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
