apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: pma-svc
  labels:
    app: pma
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: pma
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: pma_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
